export function printHelp(): void {
  console.log(`Usage:
  npm run oracle -- inspect-close-condition --market <market-id-or-key> --close-condition-satisfied true|false --source-url <url>|... --source-label <label>|... --claim-summary <text>|... [--source-type official|news|... ] [--requires-human-review true] [--review-type conflicting_sources|insufficient_evidence|wording_ambiguity|mapping_ambiguity] [--json]
  npm run oracle -- inspect-resolution --market <market-id-or-key> --source-url <url>|... --source-label <label>|... --claim-summary <text>|... [--independent-group-id <group>|...] [--winning-outcome-id <id> | --winning-outcome-key <key>] [--requires-human-review true] [--fallback-resolution true --fallback-evidence-standard <standard> --primary-source-url <url> --primary-failure-reason <reason>] [--review-type conflicting_sources|insufficient_evidence|wording_ambiguity|mapping_ambiguity] [--resolved-at-observed <iso>] [--json]
  npm run oracle -- inspect-market --market <market-id-or-key> --case-type close_condition_check|resolution_check --source-url <url>|... --source-label <label>|... --claim-summary <text>|... [other flags] [--persist false] [--json]
  npm run oracle -- review-queue [--case-status review_needed|recommended|no_action|all] [--case-type close_condition_check|resolution_check] [--market <market-id-or-key>] [--limit 20] [--json]
  npm run oracle -- resolve-inbox [--market <market-id-or-key>] [--limit 20] [--json]
  npm run oracle -- official-final-intake [--market <market-id-or-key>] [--limit 20] [--json]
  npm run oracle -- case-history --market <market-id-or-key> [--case-status review_needed|recommended|no_action|all] [--case-type close_condition_check|resolution_check] [--limit 20] [--json]
  npm run oracle -- case-detail --case <oracle-case-id> [--json]
  npm run oracle -- approve-close-condition-case --case <oracle-case-id> [--actor-id <id>] [--review-note <text>] [--idempotency-key <key>] [--json]
  npm run oracle -- approve-resolution-case --case <oracle-case-id> [--actor-id <id>] [--review-note <text>] [--idempotency-key <key>] [--json]
  npm run oracle -- reject-case --case <oracle-case-id> [--actor-id <id>] [--review-note <text>] [--idempotency-key <key>] [--json]
  npm run oracle -- request-more-evidence --case <oracle-case-id> [--actor-id <id>] [--review-note <text>] [--idempotency-key <key>] [--json]
  npm run oracle -- intake-candidate-evidence --market <market-id-or-key> --case-type close_condition_check|resolution_check --signal-id <id> --source-id <id> --source-label <label> --source-url <url> --title <title> --summary <summary> --observed-at <iso> [--winning-outcome-key <key>] [--close-condition-satisfied true|false] [--json]
  npm run oracle -- intake-credible-report --market <market-id-or-key> --source-id <credible-source-id> --source-url <url> --claim-summary <text> --winning-outcome-key <key> --observed-at <iso> [--source-label <label>] [--json]
  npm run oracle -- approve-resolution-candidate --market <market-id-or-key> --signal-id <id> --source-id <id> --source-label <label> --source-url <url> --title <title> --summary <summary> --observed-at <iso> --winning-outcome-key <key> [--review-note <text>] [--idempotency-key <key>] [--json]
  npm run oracle -- operator-resolve --market <market-id-or-key> --mode test|official|manual --winning-outcome-key <key> --reason-summary <text> --evidence-url <url-or-local-ref> --evidence-label <label> [--claim-summary <text>] [--approve true] [--review-note <text>] [--idempotency-key <key>] [--json]
  npm run oracle -- operator-observed-event --market <market-id-or-key> --summary <text> [--observed-outcome-key <key>] [--source-url <url>] [--source-label <label>] [--observed-at <iso>] [--note <text>] [--idempotency-key <key>] [--json]
  npm run oracle -- void-market --market <market-id-or-key> --reason <text> [--note <text>] [--requested-at <iso>] [--idempotency-key <key>] [--json]
  npm run oracle -- capture-tradingview-fx-snapshot --market <market-id-or-key> --symbol <EURUSD|USDILS|EURILS> [--observed-at <iso>] [--idempotency-key <key>] [--json]
  npm run oracle -- credible-reporting-evaluate --market <market-id-or-key> [--dry-run true] [--json]
  npm run oracle -- family-route-audit [--source-id <id>] [--json]
  npm run oracle -- capability-check --source-id <id> --measurement <measurementKind> --shape <resultShape> [--source-url <url>] [--json]
  npm run oracle -- alerts [--market-status open|closed|all] [--review-stale-hours 6] [--recommended-stale-hours 12] [--closed-resolution-grace-hours 2] [--preclose-fetch-gap-hours 24] [--json]
  npm run oracle -- lifecycle-run [--market <market-id-or-key>] [--limit 20] [--dry-run true] [--now <iso>] [--json]
  npm run oracle -- lifecycle-heartbeat [--market <market-id-or-key>] [--limit 20] [--dry-run true] [--max-ticks 1] [--interval-ms 300000] [--operator-reminders true] [--require-lock false] [--now <iso>] [--json|--jsonl]
`);
}
