import type { SourceRegistryEntry } from "../contracts";

export const seededSeerSourceRegistry: SourceRegistryEntry[] = [
  {
    objectType: "source_registry_entry",
    sourceId: "src_polymarket_market_reference",
    label: "Polymarket public market reference",
    ownerLabel: "Polymarket",
    homepage: "https://polymarket.com/",
    primaryClass: "context",
    accessSurface: "api",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["general", "politics", "economy", "sports", "culture"],
    primaryJobs: ["explain-context", "shape-wording"],
    speedProfile: "fast",
    noiseProfile: "medium",
    authorityProfile: "medium",
    domainNotes: ["Reference-only external market shape teacher. Not a resolution anchor and not a heartbeat event source."],
    seerPath: "platform-shape-reference",
    createdAt: "2026-04-08T15:00:00Z",
    updatedAt: "2026-04-08T15:00:00Z",
    flags: ["live-fetch", "reference-only"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_kalshi_market_reference",
    label: "Kalshi public market reference",
    ownerLabel: "Kalshi",
    homepage: "https://kalshi.com/",
    primaryClass: "context",
    accessSurface: "api",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["general", "politics", "economy", "sports", "culture"],
    primaryJobs: ["explain-context", "shape-wording"],
    speedProfile: "fast",
    noiseProfile: "medium",
    authorityProfile: "medium",
    domainNotes: ["Reference-only external market shape teacher. Use Kalshi API, not homepage scraping, on this machine/runtime path."],
    seerPath: "platform-shape-reference",
    createdAt: "2026-04-08T15:00:00Z",
    updatedAt: "2026-04-08T15:00:00Z",
    flags: ["live-fetch", "reference-only"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_credible_reporting_bundle",
    label: "Credible reporting source bundle",
    ownerLabel: "Hachozeh Oracle",
    homepage: "internal://oracle/credible-reporting",
    primaryClass: "internal",
    accessSurface: "manual-import",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["general", "politics", "security", "economy", "culture", "sports"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "medium",
    authorityProfile: "high",
    credibleReporting: {
      allowed: true,
      tier: "primary",
      notes: ["Policy evaluator for markets resolved by multiple independent credible sources."]
    },
    domainNotes: [
      "Not a scraped publisher. Contracts must list approved external sources in oracle_source_policy.credibleReporting.",
      "Oracle may create recommended cases only after independent-source agreement; trusted resolve still requires operator approval."
    ],
    lifecycleCapabilities: [
      {
        measurementKind: "reported_claim",
        resultShape: "yes_no",
        oracleCapability: "credible_reporting",
        notes: ["Human-gated credible-reporting evaluator; no auto-resolution."]
      },
      {
        measurementKind: "reported_claim",
        resultShape: "multi_outcome",
        oracleCapability: "credible_reporting",
        notes: ["Human-gated credible-reporting evaluator; no auto-resolution."]
      }
    ],
    seerPath: "credible-reporting-policy-evaluator",
    createdAt: "2026-05-22T09:00:00Z",
    updatedAt: "2026-05-22T09:00:00Z",
    flags: ["manual-import", "human-review-required", "credible-reporting"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_reuters",
    label: "Reuters",
    ownerLabel: "Reuters",
    homepage: "https://www.reuters.com/",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["general", "politics", "security", "economy", "sports", "culture"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "fast",
    noiseProfile: "medium",
    authorityProfile: "high",
    independentGroupId: "reuters",
    domainPatterns: ["reuters.com"],
    credibleReporting: {
      allowed: true,
      tier: "primary",
      notes: ["International wire source; count as Reuters independent group."]
    },
    domainNotes: ["Credible-reporting source only; not an official/canonical resolver."],
    seerPath: "credible-reporting-source",
    createdAt: "2026-05-25T06:00:00Z",
    updatedAt: "2026-05-25T06:00:00Z",
    flags: ["manual-import", "credible-reporting"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_ap",
    label: "Associated Press",
    ownerLabel: "Associated Press",
    homepage: "https://apnews.com/",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["general", "politics", "security", "economy", "sports", "culture"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "fast",
    noiseProfile: "medium",
    authorityProfile: "high",
    independentGroupId: "associated-press",
    domainPatterns: ["apnews.com"],
    credibleReporting: {
      allowed: true,
      tier: "primary",
      notes: ["International wire source; count as Associated Press independent group."]
    },
    domainNotes: ["Credible-reporting source only; not an official/canonical resolver."],
    seerPath: "credible-reporting-source",
    createdAt: "2026-05-25T06:00:00Z",
    updatedAt: "2026-05-25T06:00:00Z",
    flags: ["manual-import", "credible-reporting"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_kan_news",
    label: "Kan News",
    ownerLabel: "Kan",
    homepage: "https://www.kan.org.il/",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["general", "politics", "security", "economy", "culture", "sports"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "fast",
    noiseProfile: "medium",
    authorityProfile: "high",
    independentGroupId: "kan",
    domainPatterns: ["kan.org.il"],
    credibleReporting: {
      allowed: true,
      tier: "primary",
      notes: ["Israeli public broadcaster; prefer original reporting over wire reposts."]
    },
    domainNotes: ["Credible-reporting source only unless the market contract names Kan as the explicit authority."],
    seerPath: "credible-reporting-source",
    createdAt: "2026-05-25T06:00:00Z",
    updatedAt: "2026-05-25T06:00:00Z",
    flags: ["manual-import", "credible-reporting", "local-priority"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_channel12_news",
    label: "Channel 12 News",
    ownerLabel: "Keshet 12",
    homepage: "https://www.mako.co.il/news",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["general", "politics", "security", "economy", "culture"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "fast",
    noiseProfile: "medium",
    authorityProfile: "high",
    independentGroupId: "keshet-12",
    domainPatterns: ["mako.co.il", "n12.co.il"],
    credibleReporting: {
      allowed: true,
      tier: "supporting",
      notes: ["Israeli newsroom; count under Keshet 12 independent group."]
    },
    domainNotes: ["Credible-reporting source only; watch for wire/cross-posted material."],
    seerPath: "credible-reporting-source",
    createdAt: "2026-05-25T06:00:00Z",
    updatedAt: "2026-05-25T06:00:00Z",
    flags: ["manual-import", "credible-reporting", "local-priority"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_channel13_news",
    label: "Channel 13 News",
    ownerLabel: "Reshet 13",
    homepage: "https://13tv.co.il/news/",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["general", "politics", "security", "economy", "culture"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "fast",
    noiseProfile: "medium",
    authorityProfile: "high",
    independentGroupId: "reshet-13",
    domainPatterns: ["13tv.co.il"],
    credibleReporting: {
      allowed: true,
      tier: "supporting",
      notes: ["Israeli newsroom; count under Reshet 13 independent group."]
    },
    domainNotes: ["Credible-reporting source only; watch for wire/cross-posted material."],
    seerPath: "credible-reporting-source",
    createdAt: "2026-05-25T06:00:00Z",
    updatedAt: "2026-05-25T06:00:00Z",
    flags: ["manual-import", "credible-reporting", "local-priority"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_ynet_news",
    label: "Ynet",
    ownerLabel: "Yedioth Ahronoth",
    homepage: "https://www.ynet.co.il/",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["general", "politics", "security", "economy", "culture", "sports"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "fast",
    noiseProfile: "medium",
    authorityProfile: "high",
    independentGroupId: "yedioth",
    domainPatterns: ["ynet.co.il"],
    credibleReporting: {
      allowed: true,
      tier: "supporting",
      notes: ["Yedioth group source; do not count independently from Calcalist."]
    },
    domainNotes: ["Credible-reporting source only; shares independence group with Calcalist."],
    seerPath: "credible-reporting-source",
    createdAt: "2026-05-25T06:00:00Z",
    updatedAt: "2026-05-25T06:00:00Z",
    flags: ["manual-import", "credible-reporting", "local-priority"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_calcalist_news",
    label: "Calcalist",
    ownerLabel: "Yedioth Ahronoth",
    homepage: "https://www.calcalist.co.il/",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["economy", "technology", "general"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "fast",
    noiseProfile: "medium",
    authorityProfile: "high",
    independentGroupId: "yedioth",
    domainPatterns: ["calcalist.co.il"],
    credibleReporting: {
      allowed: true,
      tier: "supporting",
      notes: ["Yedioth group source; do not count independently from Ynet."]
    },
    domainNotes: ["Credible-reporting source only; shares independence group with Ynet."],
    seerPath: "credible-reporting-source",
    createdAt: "2026-05-25T06:00:00Z",
    updatedAt: "2026-05-25T06:00:00Z",
    flags: ["manual-import", "credible-reporting", "local-priority"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_walla_news",
    label: "Walla News",
    ownerLabel: "Walla",
    homepage: "https://news.walla.co.il/",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["general", "politics", "security", "economy", "culture", "sports"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "fast",
    noiseProfile: "medium",
    authorityProfile: "high",
    independentGroupId: "walla",
    domainPatterns: ["walla.co.il"],
    credibleReporting: {
      allowed: true,
      tier: "supporting",
      notes: ["Israeli newsroom; count under Walla independent group."]
    },
    domainNotes: ["Credible-reporting source only; watch for syndicated material."],
    seerPath: "credible-reporting-source",
    createdAt: "2026-05-25T06:00:00Z",
    updatedAt: "2026-05-25T06:00:00Z",
    flags: ["manual-import", "credible-reporting", "local-priority"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_haaretz_news",
    label: "Haaretz",
    ownerLabel: "Haaretz",
    homepage: "https://www.haaretz.co.il/",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["general", "politics", "security", "economy", "culture"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "medium",
    noiseProfile: "medium",
    authorityProfile: "high",
    independentGroupId: "haaretz",
    domainPatterns: ["haaretz.co.il", "haaretz.com"],
    credibleReporting: {
      allowed: true,
      tier: "supporting",
      notes: ["Israeli newsroom; count under Haaretz independent group."]
    },
    domainNotes: ["Credible-reporting source only; paywall/access constraints may require manual import."],
    seerPath: "credible-reporting-source",
    createdAt: "2026-05-25T06:00:00Z",
    updatedAt: "2026-05-25T06:00:00Z",
    flags: ["manual-import", "credible-reporting", "local-priority"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_globes_news",
    label: "Globes",
    ownerLabel: "Globes",
    homepage: "https://www.globes.co.il/",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["economy", "technology", "general"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "medium",
    noiseProfile: "medium",
    authorityProfile: "high",
    independentGroupId: "globes",
    domainPatterns: ["globes.co.il"],
    credibleReporting: {
      allowed: true,
      tier: "supporting",
      notes: ["Israeli business newsroom; count under Globes independent group."]
    },
    domainNotes: ["Credible-reporting source only; useful for economy/business claims."],
    seerPath: "credible-reporting-source",
    createdAt: "2026-05-25T06:00:00Z",
    updatedAt: "2026-05-25T06:00:00Z",
    flags: ["manual-import", "credible-reporting", "local-priority"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_themarker_news",
    label: "TheMarker",
    ownerLabel: "Haaretz",
    homepage: "https://www.themarker.com/",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["economy", "technology", "general"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "medium",
    noiseProfile: "medium",
    authorityProfile: "high",
    independentGroupId: "haaretz",
    domainPatterns: ["themarker.com", "themarker.co.il"],
    credibleReporting: {
      allowed: true,
      tier: "supporting",
      notes: ["Haaretz group business source; do not count independently from Haaretz."]
    },
    domainNotes: ["Credible-reporting source only; useful for business/platform coverage claims."],
    seerPath: "gta-vi-israel-event-source-hardening",
    createdAt: "2026-06-30T00:00:00Z",
    updatedAt: "2026-06-30T00:00:00Z",
    flags: ["manual-import", "credible-reporting", "local-priority"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_maariv_news",
    label: "Maariv",
    ownerLabel: "Maariv",
    homepage: "https://www.maariv.co.il/",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["general", "politics", "security", "economy", "culture", "sports"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "medium",
    noiseProfile: "medium",
    authorityProfile: "high",
    independentGroupId: "maariv",
    domainPatterns: ["maariv.co.il"],
    credibleReporting: {
      allowed: true,
      tier: "supporting",
      notes: ["Israeli newsroom; count under Maariv independent group."]
    },
    domainNotes: ["Credible-reporting source only; watch for syndicated material."],
    seerPath: "gta-vi-israel-event-source-hardening",
    createdAt: "2026-06-30T00:00:00Z",
    updatedAt: "2026-06-30T00:00:00Z",
    flags: ["manual-import", "credible-reporting", "local-priority"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_israel_hayom_news",
    label: "Israel Hayom",
    ownerLabel: "Israel Hayom",
    homepage: "https://www.israelhayom.co.il/",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["general", "politics", "security", "economy", "culture", "sports"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "medium",
    noiseProfile: "medium",
    authorityProfile: "high",
    independentGroupId: "israel-hayom",
    domainPatterns: ["israelhayom.co.il"],
    credibleReporting: {
      allowed: true,
      tier: "supporting",
      notes: ["Israeli newsroom; count under Israel Hayom independent group."]
    },
    domainNotes: ["Credible-reporting source only; watch for syndicated material."],
    seerPath: "gta-vi-israel-event-source-hardening",
    createdAt: "2026-06-30T00:00:00Z",
    updatedAt: "2026-06-30T00:00:00Z",
    flags: ["manual-import", "credible-reporting", "local-priority"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_google_trending_il",
    label: "Google Trending IL",
    ownerLabel: "Google Trends",
    homepage: "https://trends.google.com/trending?geo=IL",
    primaryClass: "attention",
    accessSurface: "rss",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["sensing", "grounding"],
    categoryFit: ["general", "news", "sports", "politics", "culture"],
    primaryJobs: ["notice-motion", "spot-weak-signals", "reactivate-lineage"],
    speedProfile: "fast",
    noiseProfile: "high",
    authorityProfile: "low",
    domainNotes: ["Heartbeat attention feed for what is actively trending in Israel right now."],
    seerPath: "heartbeat-google-trending-il",
    createdAt: "2026-04-08T10:00:00Z",
    updatedAt: "2026-04-08T10:00:00Z",
    flags: ["live-fetch"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_home_front_command",
    label: "Home Front Command alerts and updates",
    ownerLabel: "Home Front Command",
    homepage: "https://www.oref.org.il/en",
    primaryClass: "authority",
    accessSurface: "api",
    status: "paused",
    curationMode: "manual-seed",
    stageUsefulness: ["sensing", "grounding", "review"],
    categoryFit: ["security", "general"],
    primaryJobs: ["notice-motion", "ground-confidence", "anchor-resolution"],
    speedProfile: "fast",
    noiseProfile: "low",
    authorityProfile: "official",
    domainNotes: ["Primary civilian alert layer for Israeli security and disruption events."],
    seerPath: "research-seeded-fetch-roadmap",
    createdAt: "2026-04-08T11:00:00Z",
    updatedAt: "2026-04-08T11:00:00Z",
    flags: ["paused-local-focus"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_gov_il_news",
    label: "gov.il department news",
    ownerLabel: "Gov.il",
    homepage: "https://www.gov.il/en/departments/news",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["politics", "economy", "security", "general"],
    primaryJobs: ["notice-motion", "ground-confidence", "anchor-resolution"],
    speedProfile: "medium",
    noiseProfile: "medium",
    authorityProfile: "official",
    domainNotes: ["Central government publication layer for ministry and agency updates."],
    lifecycleCapabilities: [
      {
        measurementKind: "official_value",
        resultShape: "yes_no",
        oracleCapability: "manual_resolution_required",
        notes: ["Official source is suitable for contract grounding; gov.il page-specific parsing is not built yet."]
      },
      {
        measurementKind: "deadline_yes_no",
        resultShape: "yes_no",
        oracleCapability: "manual_resolution_required",
        notes: ["Use for official-publication-before-deadline markets only with an exact department/page URL."]
      }
    ],
    seerPath: "research-seeded-fetch-roadmap",
    createdAt: "2026-04-08T11:00:00Z",
    updatedAt: "2026-04-08T11:00:00Z",
    flags: ["planned-fetch", "verification-first"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_knesset_official",
    label: "Knesset official",
    ownerLabel: "The Knesset",
    homepage: "https://main.knesset.gov.il/",
    primaryClass: "authority",
    accessSurface: "api",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["politics"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "medium",
    authorityProfile: "official",
    domainNotes: ["Official Knesset layer for dissolution votes, legislative clock, and related parliamentary procedure."],
    lifecycleCapabilities: [
      {
        measurementKind: "deadline_yes_no",
        resultShape: "yes_no",
        oracleCapability: "supported_full_cycle",
        notes: [
          "Knesset legislation official source adapter reads the official Knesset OData bill status by bill id for lifecycle closure and final resolution; public bill page remains the trust/display URL."
        ]
      }
    ],
    seerPath: "politics-family-probe",
    createdAt: "2026-04-16T12:50:00Z",
    updatedAt: "2026-04-16T12:50:00Z",
    flags: ["planned-fetch", "verification-first", "politics-family-source"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_idf_realtime_updates",
    label: "IDF real-time updates",
    ownerLabel: "IDF",
    homepage: "https://www.idf.il/en/mini-sites/israel-at-war/real-time-updates/",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["sensing", "grounding", "review"],
    categoryFit: ["security"],
    primaryJobs: ["notice-motion", "ground-confidence", "anchor-resolution"],
    speedProfile: "fast",
    noiseProfile: "low",
    authorityProfile: "official",
    domainNotes: ["Primary military verification layer for Israeli conflict updates."],
    lifecycleCapabilities: [
      {
        measurementKind: "official_value",
        resultShape: "yes_no",
        oracleCapability: "manual_resolution_required",
        notes: ["Official security source is grounded, but IDF page parsing and sensitive-market policy review are not automated."]
      },
      {
        measurementKind: "reported_claim",
        resultShape: "yes_no",
        oracleCapability: "manual_resolution_required",
        notes: ["Use only as official evidence inside a human-reviewed security claim; do not auto-resolve."]
      }
    ],
    seerPath: "research-seeded-fetch-roadmap",
    createdAt: "2026-04-08T11:00:00Z",
    updatedAt: "2026-04-08T11:00:00Z",
    flags: ["planned-fetch", "verification-first"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_iaa_notifications",
    label: "Israel Airports Authority notifications",
    ownerLabel: "Israel Airports Authority",
    homepage: "https://www.iaa.gov.il/en/airports/ben-gurion/notifications-and-updates/",
    primaryClass: "authority",
    accessSurface: "html",
    status: "paused",
    curationMode: "manual-seed",
    stageUsefulness: ["sensing", "grounding", "review"],
    categoryFit: ["travel", "security", "general"],
    primaryJobs: ["notice-motion", "ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "low",
    authorityProfile: "official",
    domainNotes: ["Primary source for Ben Gurion and airport disruption status."],
    lifecycleCapabilities: [
      {
        measurementKind: "official_value",
        resultShape: "yes_no",
        oracleCapability: "manual_resolution_required",
        notes: ["IAA official page can ground airport-operation claims; adapter automation is not built and paired-source markets need company-side evidence."]
      },
      {
        measurementKind: "reported_claim",
        resultShape: "yes_no",
        oracleCapability: "manual_resolution_required",
        notes: ["Use as one side of a human-reviewed paired-source claim, not as a standalone automated resolver."]
      }
    ],
    seerPath: "research-seeded-fetch-roadmap",
    createdAt: "2026-04-08T11:00:00Z",
    updatedAt: "2026-04-08T11:00:00Z",
    flags: ["paused-local-focus", "verification-first"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_mda_news",
    label: "MDA official news",
    ownerLabel: "Magen David Adom",
    homepage: "https://www.mdais.org/en/news",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["security", "health", "general"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "fast",
    noiseProfile: "low",
    authorityProfile: "official",
    domainNotes: ["Official medical and casualty confirmation layer for major incidents."],
    seerPath: "research-seeded-fetch-roadmap",
    createdAt: "2026-04-08T11:00:00Z",
    updatedAt: "2026-04-08T11:00:00Z",
    flags: ["planned-fetch", "verification-first"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_mot_il_official",
    label: "Israel Ministry of Transport official publications",
    ownerLabel: "Israel Ministry of Transport and Road Safety",
    homepage: "https://www.gov.il/en/departments/ministry_of_transport_and_road_safety",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["transportation", "travel", "economy", "general"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "medium",
    authorityProfile: "official",
    domainNotes: [
      "Official Israeli regulator source for public transport, taxis, aviation, roads, and mobility policy.",
      "Market contracts must attach the exact ministry publication or department page; generic department page is only a trust surface."
    ],
    lifecycleCapabilities: [
      {
        measurementKind: "official_value",
        resultShape: "yes_no",
        oracleCapability: "manual_resolution_required",
        notes: ["Official transport-source grounding is available; exact publication parsing is not automated."]
      },
      {
        measurementKind: "deadline_yes_no",
        resultShape: "yes_no",
        oracleCapability: "manual_resolution_required",
        notes: ["Use for transport-service or regulatory-publication deadline markets with exact page evidence."]
      },
      {
        measurementKind: "reported_claim",
        resultShape: "yes_no",
        oracleCapability: "manual_resolution_required",
        notes: ["Use as Israeli-side evidence in paired-source claims; human review remains required."]
      }
    ],
    seerPath: "gta-vi-israel-event-source-hardening",
    createdAt: "2026-06-30T00:00:00Z",
    updatedAt: "2026-06-30T00:00:00Z",
    flags: ["planned-fetch", "verification-first", "requires-exact-source-url", "official-transport-source"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_airline_company_announcements",
    label: "Airline company official announcements",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["travel", "transportation", "business"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "medium",
    authorityProfile: "official",
    domainNotes: [
      "Template source id for airline newsroom, press-release, investor, or route-announcement pages.",
      "Paired-source airport-base markets require both a company-side announcement and an Israeli official confirmation."
    ],
    lifecycleCapabilities: [
      {
        measurementKind: "reported_claim",
        resultShape: "yes_no",
        oracleCapability: "manual_resolution_required",
        notes: ["Company-side evidence for paired-source claims; exact airline URL is required and human review remains required."]
      }
    ],
    seerPath: "gta-vi-israel-event-source-hardening",
    createdAt: "2026-06-30T00:00:00Z",
    updatedAt: "2026-06-30T00:00:00Z",
    flags: ["template-source", "requires-exact-source-url", "verification-first", "paired-source"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_transport_company_announcements",
    label: "Transport company official announcements",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["transportation", "technology", "business"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "medium",
    authorityProfile: "official",
    domainNotes: [
      "Template source id for taxi, private-ride, or on-demand passenger-transport service announcements.",
      "Markets must list eligible companies in visible rules and attach exact company evidence, not a generic homepage."
    ],
    lifecycleCapabilities: [
      {
        measurementKind: "reported_claim",
        resultShape: "yes_no",
        oracleCapability: "manual_resolution_required",
        notes: ["Company-side evidence for transport-service launch claims; exact company URL and human review are required."]
      }
    ],
    seerPath: "gta-vi-israel-event-source-hardening",
    createdAt: "2026-06-30T00:00:00Z",
    updatedAt: "2026-06-30T00:00:00Z",
    flags: ["template-source", "requires-exact-source-url", "verification-first", "paired-source"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_incd_alerts",
    label: "Israel National Cyber Directorate alerts",
    ownerLabel: "INCD",
    homepage: "https://www.gov.il/en/departments/israel_national_cyber_directorate",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["technology", "security", "general"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "fast",
    noiseProfile: "low",
    authorityProfile: "official",
    domainNotes: ["Integrity layer for phishing, cyber, and disinformation contradiction checks."],
    seerPath: "research-seeded-fetch-roadmap",
    createdAt: "2026-04-08T11:00:00Z",
    updatedAt: "2026-04-08T11:00:00Z",
    flags: ["planned-fetch", "verification-first"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_google_trends_israel_interest_rate",
    label: "Google Trends: Israel interest rate",
    ownerLabel: "Google Trends",
    homepage: "https://trends.google.com/",
    primaryClass: "attention",
    accessSurface: "api",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["sensing", "grounding"],
    categoryFit: ["economy"],
    primaryJobs: ["notice-motion", "spot-weak-signals"],
    speedProfile: "fast",
    noiseProfile: "medium",
    authorityProfile: "low",
    domainNotes: ["Useful as an early attention detector around rate-decision cycles."],
    lineageAffinity: ["boi-rate-decisions"],
    seerPath: "curated-seed",
    lastSeenAt: "2026-03-28T10:20:00Z",
    lastUsefulAt: "2026-03-28T10:20:00Z",
    createdAt: "2026-04-05T09:00:00Z",
    updatedAt: "2026-04-05T09:00:00Z"
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_boi_announcements",
    label: "Bank of Israel announcements",
    ownerLabel: "Bank of Israel",
    homepage: "https://www.boi.org.il/",
    primaryClass: "authority",
    accessSurface: "html",
    status: "trusted",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["economy"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "low",
    authorityProfile: "official",
    domainNotes: ["Primary authority anchor for Bank of Israel rate-decision markets."],
    lifecycleCapabilities: [
      {
        measurementKind: "rate_direction",
        resultShape: "cut_hold_hike",
        oracleCapability: "supported_final_only",
        notes: ["Oracle can inspect final Bank of Israel rate-decision publications; scheduled close remains Horizon-owned."]
      },
      {
        measurementKind: "rate_direction",
        resultShape: "yes_no",
        oracleCapability: "supported_final_only",
        notes: ["Binary BOI unchanged-rate markets map the official hold/cut/hike decision through explicit yes/no outcome keys."]
      }
    ],
    lineageAffinity: ["boi-rate-decisions"],
    seerPath: "curated-seed",
    lastSeenAt: "2026-03-28T10:22:00Z",
    lastUsefulAt: "2026-03-28T10:22:00Z",
    createdAt: "2026-04-05T09:00:00Z",
    updatedAt: "2026-04-12T20:00:00Z",
    flags: ["live-fetch", "verification-first"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_boi_exchange_rates",
    label: "Bank of Israel representative exchange rates",
    ownerLabel: "Bank of Israel",
    homepage: "https://boi.org.il/PublicApi/GetExchangeRates",
    primaryClass: "authority",
    accessSurface: "api",
    status: "trusted",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["economy"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "low",
    authorityProfile: "official",
    domainNotes: [
      "Official representative exchange-rate JSON endpoint for latest BOI FX rates.",
      "Use BOI SDMX EXR dataflow for deterministic historical replay/backfill.",
      "Representative rates are informational and may publish with short afternoon/revision lag."
    ],
    lifecycleCapabilities: [
      {
        measurementKind: "threshold_crossing",
        resultShape: "yes_no",
        oracleCapability: "supported_final_only",
        notes: ["Oracle BOI FX adapter resolves representative-rate threshold markets from BOI SDMX/current API; human approval still required."]
      },
      {
        measurementKind: "official_value",
        resultShape: "multi_outcome",
        oracleCapability: "manual_resolution_required",
        notes: ["Official source is grounded; exact/range BOI FX Oracle adapter is not built yet."]
      }
    ],
    seerPath: "economy-family-sweep",
    createdAt: "2026-05-20T12:00:00Z",
    updatedAt: "2026-05-20T12:00:00Z",
    flags: ["live-fetch", "verification-first", "official-economy-source"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_tradingview_fx",
    label: "TradingView FX price snapshots",
    ownerLabel: "TradingView",
    homepage: "https://www.tradingview.com/markets/currencies/",
    primaryClass: "authority",
    accessSurface: "api",
    status: "trusted",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["economy"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "fast",
    noiseProfile: "low",
    authorityProfile: "high",
    domainNotes: [
      "Use TradingView symbol pages as the human trust surface for live FX markets.",
      "Final-point contracts must include an exact machineResolutionEndpoint that returns a timestamped symbol price near the market close.",
      "Window-crossing contracts must include a hachozeh TradingView snapshot endpoint with from/to timestamps plus timeline.fxObservationMode=window and an explicit capture cadence.",
      "Do not use BOI representative rates as a live FX proxy."
    ],
    lifecycleCapabilities: [
      {
        measurementKind: "threshold_crossing",
        resultShape: "yes_no",
        oracleCapability: "supported_final_only",
        notes: ["Oracle TradingView FX adapter resolves timestamped live-FX threshold snapshots and opt-in windowed crossing snapshots; human approval still required."]
      },
      {
        measurementKind: "official_value",
        resultShape: "multi_outcome",
        oracleCapability: "supported_final_only",
        notes: ["Oracle TradingView FX adapter maps timestamped live-FX snapshots into listed range outcomes."]
      }
    ],
    seerPath: "economy-live-fx-family",
    createdAt: "2026-06-01T12:50:00Z",
    updatedAt: "2026-06-01T12:50:00Z",
    flags: ["live-fetch", "verification-first", "fx-source", "oracle-supported-final-only"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_cbs_time_series",
    label: "Israel CBS official time-series and price-index APIs",
    ownerLabel: "Israel Central Bureau of Statistics",
    homepage: "https://www.cbs.gov.il/en/Pages/Main%20Price%20Indices.aspx",
    primaryClass: "authority",
    accessSurface: "api",
    status: "trusted",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["economy", "education", "health"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "medium",
    authorityProfile: "official",
    domainNotes: [
      "Official CBS API surface for time series and price-index data.",
      "CPI monthly change source uses api.cbs.gov.il/index/data/price_selected?format=xml&download=false.",
      "Target CPI price-index code is 120010 (monthly CPI all-categories change).",
      "CPI/price endpoints require User-Agent and period-specific handling.",
      "Monthly CPI publication cadence and provisional/revision behavior must be modeled per series."
    ],
    lifecycleCapabilities: [
      {
        measurementKind: "official_value",
        resultShape: "multi_outcome",
        oracleCapability: "supported_final_only",
        notes: [
          "Oracle reads the CBS time-series machine endpoint for monthly CPI change and maps to configured outcome ranges.",
          "Machine endpoint must be HTTPS on api.cbs.gov.il and include the target period."
        ]
      }
    ],
    seerPath: "economy-family-sweep",
    createdAt: "2026-05-20T12:00:00Z",
    updatedAt: "2026-05-20T12:00:00Z",
    flags: ["live-fetch", "verification-first", "official-economy-source", "oracle-supported-final-only"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_news_burst_eurovision",
    label: "Eurovision news burst monitor",
    ownerLabel: "Seeded media burst",
    primaryClass: "attention",
    accessSurface: "manual-import",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["sensing", "grounding"],
    categoryFit: ["culture"],
    primaryJobs: ["notice-motion", "reactivate-lineage"],
    speedProfile: "fast",
    noiseProfile: "medium",
    authorityProfile: "low",
    domainNotes: ["Fast attention detector for recurring Eurovision winner narratives."],
    lineageAffinity: ["eurovision-winner-markets"],
    seerPath: "curated-seed",
    lastSeenAt: "2026-03-28T11:10:00Z",
    lastUsefulAt: "2026-03-28T11:10:00Z",
    createdAt: "2026-04-05T09:00:00Z",
    updatedAt: "2026-04-05T09:00:00Z"
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_eurovision_official",
    label: "Eurovision official schedule and results",
    ownerLabel: "Eurovision",
    homepage: "https://eurovision.tv/",
    primaryClass: "authority",
    accessSurface: "html",
    status: "trusted",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["culture", "entertainment", "awards"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "low",
    authorityProfile: "official",
    domainNotes: ["Primary authority anchor for Eurovision final timing and result settlement."],
    lifecycleCapabilities: [
      {
        measurementKind: "final_winner",
        resultShape: "yes_no",
        oracleCapability: "supported_final_only",
        notes: ["Oracle can inspect the official Eurovision scoreboard after final publication; scheduled close remains Horizon-owned."]
      },
      {
        measurementKind: "official_value",
        resultShape: "multi_outcome",
        oracleCapability: "supported_final_only",
        notes: ["Oracle can map official Eurovision scoreboard country winners/last-place rows through country evidence keys."]
      }
    ],
    lineageAffinity: ["eurovision-winner-markets"],
    seerPath: "curated-seed",
    lastSeenAt: "2026-03-28T11:18:00Z",
    lastUsefulAt: "2026-03-28T11:18:00Z",
    createdAt: "2026-04-05T09:00:00Z",
    updatedAt: "2026-04-05T09:00:00Z"
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_nike_liga_official",
    label: "Niké Liga official match pages",
    ownerLabel: "Niké Liga",
    homepage: "https://www.nikeliga.sk/",
    primaryClass: "authority",
    accessSurface: "html",
    status: "trusted",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["sports"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "low",
    authorityProfile: "official",
    domainNotes: ["Official Slovak top-flight football match pages; useful for gauntlet/sports parser proving before Israeli football adapter work."],
    lifecycleCapabilities: [
      {
        measurementKind: "final_winner",
        resultShape: "home_away_winner",
        oracleCapability: "supported_full_cycle",
        notes: ["Oracle Niké Liga adapter supports source-start/final-result handling for binary match winner markets."]
      },
      {
        measurementKind: "final_winner",
        resultShape: "three_way_result",
        oracleCapability: "supported_full_cycle",
        notes: ["Oracle Niké Liga adapter supports regulation-time home/draw/away result markets."]
      }
    ],
    seerPath: "sports-adapter-proof",
    createdAt: "2026-05-19T14:55:00Z",
    updatedAt: "2026-05-19T14:55:00Z",
    flags: ["live-fetch", "verification-first", "official-sports-result-source"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_fifa_match_centre",
    label: "פיפ״א, עמוד המשחק הרשמי",
    ownerLabel: "FIFA",
    homepage: "https://www.fifa.com/en/match-centre",
    primaryClass: "authority",
    accessSurface: "api",
    status: "trusted",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["sports"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "low",
    authorityProfile: "official",
    domainNotes: [
      "Primary official layer for FIFA tournament match pages, fixtures, live status, and final scores.",
      "Contracts must include an exact FIFA match-centre URL with competition, season, stage, and match ids.",
      "Oracle fetches the matching FIFA calendar payload from api.fifa.com and filters by IdMatch."
    ],
    lifecycleCapabilities: [
      {
        measurementKind: "final_winner",
        resultShape: "home_away_winner",
        oracleCapability: "supported_full_cycle",
        notes: ["Oracle FIFA adapter supports source-start/final-result handling for official FIFA match winner markets."]
      },
      {
        measurementKind: "final_winner",
        resultShape: "three_way_result",
        oracleCapability: "supported_full_cycle",
        notes: ["Oracle FIFA adapter supports regulation-time home/draw/away result markets from official FIFA match payloads."]
      }
    ],
    seerPath: "fifa-match-centre-sports-pack",
    createdAt: "2026-06-17T00:00:00Z",
    updatedAt: "2026-06-17T00:00:00Z",
    flags: ["live-fetch", "verification-first", "official-sports-result-source"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_wimbledon_official",
    label: "ווימבלדון, האתר הרשמי",
    ownerLabel: "The Championships, Wimbledon",
    homepage: "https://www.wimbledon.com/",
    primaryClass: "authority",
    accessSurface: "api",
    status: "trusted",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["sports"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "low",
    authorityProfile: "official",
    domainNotes: [
      "Primary official layer for Wimbledon schedule, draw, match status, and final result data.",
      "Oracle uses Wimbledon public GraphQL data from the official site and filters by official match ids or player names.",
      "Tournament-winner child markets may resolve NO on official elimination and YES on official final victory."
    ],
    lifecycleCapabilities: [
      {
        measurementKind: "final_winner",
        resultShape: "home_away_winner",
        oracleCapability: "supported_full_cycle",
        notes: ["Oracle Wimbledon adapter supports official match winner markets from official Wimbledon schedule payloads."]
      },
      {
        measurementKind: "final_winner",
        resultShape: "yes_no",
        oracleCapability: "supported_full_cycle",
        notes: ["Oracle Wimbledon adapter supports tournament-winner children through official elimination/final result evidence."]
      }
    ],
    seerPath: "wimbledon-official-sports-pack",
    createdAt: "2026-07-09T00:00:00Z",
    updatedAt: "2026-07-09T00:00:00Z",
    flags: ["live-fetch", "verification-first", "official-sports-result-source"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_ifa_fixtures_results",
    label: "Israel Football Association fixtures and results",
    ownerLabel: "Israel Football Association",
    homepage: "https://www.football.org.il/en/",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["sports"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "low",
    authorityProfile: "official",
    domainNotes: [
      "Primary official layer for Israeli football fixtures, results, and competition status.",
      "Oracle IFA adapter can parse official fixture/result HTML when the page is available.",
      "Direct shell/runtime fetch may still be Cloudflare-blocked from this workstation; keep fetch-bridge risk visible before unattended gauntlets."
    ],
    lifecycleCapabilities: [
      {
        measurementKind: "final_winner",
        resultShape: "three_way_result",
        oracleCapability: "supported_final_only",
        notes: ["Oracle IFA adapter supports final-result parsing for 90-minute home/draw/away markets; scheduled close remains Horizon-owned."]
      },
      {
        measurementKind: "official_value",
        resultShape: "multi_outcome",
        oracleCapability: "supported_final_only",
        notes: ["Oracle IFA adapter supports final score total-goals buckets through outcomeMap evidence keys."]
      }
    ],
    seerPath: "local-israeli-sports-pack",
    createdAt: "2026-04-14T08:00:00Z",
    updatedAt: "2026-05-25T00:00:00Z",
    flags: ["adapter-final-only", "verification-first", "official-sports-result-source", "cloudflare-fetch-risk"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_ibba_schedules",
    label: "Israel Basketball Association schedules and cups",
    ownerLabel: "Israel Basketball Association",
    homepage: "https://ibasketball.co.il/",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["sports"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "low",
    authorityProfile: "official",
    domainNotes: [
      "Primary official layer for Israeli basketball schedules, cup windows, and competition circulars.",
      "Homepage, RSS, and WordPress JSON look fetchable on this machine path."
    ],
    lifecycleCapabilities: [
      {
        measurementKind: "final_winner",
        resultShape: "home_away_winner",
        oracleCapability: "supported_full_cycle",
        notes: ["Oracle IBBA Sportspress adapter can inspect event-start/close and final winner from official event data."]
      }
    ],
    seerPath: "local-israeli-sports-pack",
    createdAt: "2026-04-14T08:00:00Z",
    updatedAt: "2026-05-20T11:20:00Z",
    flags: ["live-fetch", "verification-first", "planned-event-source", "oracle-supported-full-cycle"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_winner_league_basketball",
    label: "Winner League basketball fixtures and results",
    ownerLabel: "Winner League",
    homepage: "https://basket.co.il/",
    primaryClass: "authority",
    accessSurface: "html",
    status: "trusted",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["sports"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "medium",
    authorityProfile: "official",
    domainNotes: [
      "Top-flight Israeli basketball fixture and result layer when IBBA structure is too broad or delayed.",
      "Current official web surface exposes fixture truth through basket.co.il pbp/json config + games feeds."
    ],
    lifecycleCapabilities: [
      {
        measurementKind: "final_winner",
        resultShape: "home_away_winner",
        oracleCapability: "supported_full_cycle",
        notes: ["Oracle supports scheduled/source close checks and final winner resolution through the official games feed."]
      }
    ],
    seerPath: "local-israeli-sports-pack",
    createdAt: "2026-04-14T08:00:00Z",
    updatedAt: "2026-04-16T12:45:00Z",
    flags: ["live-fetch", "verification-first", "planned-event-source", "active-local-sports-lane"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_nba_official_games",
    label: "NBA official games",
    ownerLabel: "NBA",
    homepage: "https://www.nba.com/games",
    primaryClass: "authority",
    accessSurface: "html",
    status: "trusted",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["sports"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "low",
    authorityProfile: "official",
    domainNotes: ["Official NBA schedule and game result pages for the closed-beta platform-rooting proof market."],
    lifecycleCapabilities: [
      {
        measurementKind: "final_winner",
        resultShape: "home_away_winner",
        oracleCapability: "supported_full_cycle",
        notes: ["Oracle NBA official-game adapter is the proven closed-beta full-cycle path."]
      }
    ],
    seerPath: "closed-beta-platform-rooting",
    createdAt: "2026-05-03T18:15:00Z",
    updatedAt: "2026-05-03T18:15:00Z",
    flags: ["verification-first", "planned-event-source", "closed-beta-proof-source"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_fiba_basketball_games",
    label: "FIBA official basketball games",
    ownerLabel: "FIBA",
    homepage: "https://www.fiba.basketball/en/events",
    primaryClass: "authority",
    accessSurface: "html",
    status: "trusted",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["sports"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "low",
    authorityProfile: "official",
    domainNotes: ["Official FIBA event game pages expose scheduled time, live state, final score, and team identities."],
    lifecycleCapabilities: [
      {
        measurementKind: "final_winner",
        resultShape: "home_away_winner",
        oracleCapability: "supported_full_cycle",
        notes: ["Oracle FIBA game-page adapter can inspect event-start/close and final winner from official page data."]
      }
    ],
    seerPath: "international-basketball-national-team-pack",
    createdAt: "2026-06-22T00:00:00Z",
    updatedAt: "2026-06-22T00:00:00Z",
    flags: ["live-fetch", "verification-first", "planned-event-source", "oracle-supported-full-cycle"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_coinbase_exchange_candles",
    label: "Coinbase Exchange market candles",
    ownerLabel: "Coinbase Exchange",
    homepage: "https://docs.cdp.coinbase.com/exchange/reference/exchangerestapi_getproductcandles",
    primaryClass: "authority",
    accessSurface: "api",
    status: "trusted",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["economy", "crypto"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "low",
    authorityProfile: "official",
    domainNotes: ["Official Coinbase Exchange daily candle endpoint for UTC crypto close markets."],
    lifecycleCapabilities: [
      {
        measurementKind: "threshold_crossing",
        resultShape: "yes_no",
        oracleCapability: "supported_final_only",
        notes: ["Oracle Coinbase candle adapter resolves daily close threshold markets; human approval still required."]
      },
      {
        measurementKind: "official_value",
        resultShape: "multi_outcome",
        oracleCapability: "supported_final_only",
        notes: ["Oracle Coinbase candle adapter maps the official daily close into listed range outcomes."]
      }
    ],
    seerPath: "crypto-daily-close-family",
    createdAt: "2026-05-13T08:30:00Z",
    updatedAt: "2026-05-13T08:30:00Z",
    flags: ["verification-first", "crypto-source", "oracle-supported-final-only"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_https_www_binance_com_en_markets_overview",
    label: "Binance spot trading pairs",
    ownerLabel: "Binance",
    homepage: "https://www.binance.com/en/markets/overview",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["crypto", "economy"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "fast",
    noiseProfile: "medium",
    authorityProfile: "high",
    domainNotes: [
      "Crypto spot-market reference used by older overnight up/down gauntlet markets.",
      "Manual-resolution only until a concrete Binance candle/source adapter and exchange-close policy are built."
    ],
    lifecycleCapabilities: [
      {
        measurementKind: "threshold_crossing",
        resultShape: "yes_no",
        oracleCapability: "manual_resolution_required",
        notes: ["Classified crypto threshold source; not autonomous until a Binance candle adapter exists."]
      }
    ],
    seerPath: "crypto-daily-close-family",
    createdAt: "2026-06-22T17:30:00Z",
    updatedAt: "2026-06-22T17:30:00Z",
    flags: ["verification-first", "crypto-source", "manual-resolution-required"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_ita_tournaments",
    label: "Israel Tennis Association tournaments",
    ownerLabel: "Israel Tennis Association",
    homepage: "https://ita.co.il/",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["sports"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "low",
    authorityProfile: "official",
    domainNotes: ["Official local-tennis layer for tournament windows, draws, and championship timing."],
    seerPath: "local-israeli-sports-pack",
    createdAt: "2026-04-14T08:00:00Z",
    updatedAt: "2026-04-14T08:00:00Z",
    flags: ["planned-fetch", "verification-first", "planned-event-source"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_sport5_local_sports",
    label: "Sport5 local sports coverage",
    ownerLabel: "Sport5",
    homepage: "https://www.sport5.co.il/",
    primaryClass: "attention",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["sensing", "grounding"],
    categoryFit: ["sports"],
    primaryJobs: ["notice-motion", "reactivate-lineage", "spot-weak-signals"],
    speedProfile: "fast",
    noiseProfile: "medium",
    authorityProfile: "low",
    domainNotes: ["Local Israeli sports wake source. Useful for derby buzz and lineup pressure, not as final settlement truth."],
    seerPath: "local-israeli-sports-pack",
    createdAt: "2026-04-14T08:00:00Z",
    updatedAt: "2026-04-14T08:00:00Z",
    flags: ["planned-fetch", "wake-only"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_one_local_sports",
    label: "ONE local sports coverage",
    ownerLabel: "ONE",
    homepage: "https://www.one.co.il/",
    primaryClass: "attention",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["sensing", "grounding"],
    categoryFit: ["sports"],
    primaryJobs: ["notice-motion", "reactivate-lineage", "spot-weak-signals"],
    speedProfile: "fast",
    noiseProfile: "medium",
    authorityProfile: "low",
    domainNotes: ["Local Israeli sports wake source. Good for gossip/buzz, not official fixture or result truth."],
    seerPath: "local-israeli-sports-pack",
    createdAt: "2026-04-14T08:00:00Z",
    updatedAt: "2026-04-14T08:00:00Z",
    flags: ["planned-fetch", "wake-only"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_usgs_alerts",
    label: "USGS alerts and notifications",
    ownerLabel: "USGS",
    homepage: "https://www.usgs.gov/products/web-tools/alerts-and-notification-services",
    primaryClass: "authority",
    accessSurface: "api",
    status: "paused",
    curationMode: "manual-seed",
    stageUsefulness: ["sensing", "grounding", "review"],
    categoryFit: ["science", "general"],
    primaryJobs: ["notice-motion", "ground-confidence", "anchor-resolution"],
    speedProfile: "fast",
    noiseProfile: "low",
    authorityProfile: "official",
    domainNotes: ["Primary physical-reality layer for earthquakes, volcanoes, and hazard confirmation."],
    seerPath: "research-seeded-fetch-roadmap",
    createdAt: "2026-04-08T11:00:00Z",
    updatedAt: "2026-04-08T11:00:00Z",
    flags: ["paused-local-focus"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_gdacs_alerts",
    label: "GDACS global disaster alerts",
    ownerLabel: "GDACS",
    homepage: "https://gdacs.org/",
    primaryClass: "authority",
    accessSurface: "rss",
    status: "paused",
    curationMode: "manual-seed",
    stageUsefulness: ["sensing", "grounding", "review"],
    categoryFit: ["science", "general"],
    primaryJobs: ["notice-motion", "ground-confidence", "anchor-resolution"],
    speedProfile: "fast",
    noiseProfile: "low",
    authorityProfile: "official",
    domainNotes: ["Global disaster coordination layer for storms, floods, and major hazards."],
    seerPath: "research-seeded-fetch-roadmap",
    createdAt: "2026-04-08T11:00:00Z",
    updatedAt: "2026-04-08T11:00:00Z",
    flags: ["paused-local-focus"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_federal_reserve_rss",
    label: "Federal Reserve RSS feeds",
    ownerLabel: "Federal Reserve",
    homepage: "https://www.federalreserve.gov/feeds/feeds.htm",
    primaryClass: "authority",
    accessSurface: "rss",
    status: "paused",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["economy"],
    primaryJobs: ["notice-motion", "ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "low",
    authorityProfile: "official",
    domainNotes: ["Official US macro-policy layer for rates, facilities, and regulatory actions."],
    lifecycleCapabilities: [
      {
        measurementKind: "rate_direction",
        resultShape: "cut_hold_hike",
        oracleCapability: "blocked",
        notes: ["Do not publish as an autonomous lifecycle market until a Fed rate-decision Oracle adapter exists."]
      }
    ],
    seerPath: "research-seeded-fetch-roadmap",
    createdAt: "2026-04-08T11:00:00Z",
    updatedAt: "2026-04-08T11:00:00Z",
    flags: ["paused-local-focus"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_ecb_rss",
    label: "ECB RSS news feeds",
    ownerLabel: "European Central Bank",
    homepage: "https://www.ecb.europa.eu/home/html/rss.en.html",
    primaryClass: "authority",
    accessSurface: "rss",
    status: "paused",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["economy"],
    primaryJobs: ["notice-motion", "ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "low",
    authorityProfile: "official",
    domainNotes: ["Official eurozone macro-policy layer for ECB announcements and decisions."],
    lifecycleCapabilities: [
      {
        measurementKind: "rate_direction",
        resultShape: "cut_hold_hike",
        oracleCapability: "blocked",
        notes: ["Do not publish as an autonomous lifecycle market until an ECB rate-decision Oracle adapter exists."]
      }
    ],
    seerPath: "research-seeded-fetch-roadmap",
    createdAt: "2026-04-08T11:00:00Z",
    updatedAt: "2026-04-08T11:00:00Z",
    flags: ["paused-local-focus"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_il_election_committee_results",
    label: "Central Elections Committee official results",
    ownerLabel: "Central Elections Committee",
    homepage: "https://bechirot.gov.il/",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["politics"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "low",
    authorityProfile: "official",
    domainNotes: [
      "Official election authority for Knesset results and mandate allocation.",
      "Election-specific result sites can move by cycle; contracts must attach the exact cycle URL before publish."
    ],
    seerPath: "category-family-map-v1",
    createdAt: "2026-05-20T12:30:00Z",
    updatedAt: "2026-05-20T12:30:00Z",
    flags: ["planned-fetch", "verification-first", "official-politics-source"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_reshumot_official",
    label: "Reshumot official gazette",
    ownerLabel: "Ministry of Justice",
    homepage: "https://www.gov.il/he/departments/dynamiccollectors/gazette-official",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["legislation", "politics"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "low",
    authorityProfile: "official",
    domainNotes: [
      "Official gov.il collector for Reshumot publications.",
      "Good final publication anchor for laws/regulations; adapter needs PDF/listing parsing and exact publication-type mapping."
    ],
    seerPath: "category-family-map-v1",
    createdAt: "2026-05-20T12:30:00Z",
    updatedAt: "2026-05-20T12:30:00Z",
    flags: ["planned-fetch", "verification-first", "official-legislation-source"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_imf_sdmx",
    label: "IMF SDMX data services",
    ownerLabel: "International Monetary Fund",
    homepage: "https://sdmxcentral.imf.org/",
    primaryClass: "authority",
    accessSurface: "api",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["economy"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "medium",
    authorityProfile: "official",
    domainNotes: [
      "Official IMF SDMX surface for macro time-series families.",
      "Adapter work must pin dataset/dataflow and revision policy per market; SDMX dimensions are not one-size-fits-all."
    ],
    seerPath: "category-family-map-v1",
    createdAt: "2026-05-20T12:30:00Z",
    updatedAt: "2026-05-20T12:30:00Z",
    flags: ["planned-fetch", "verification-first", "official-economy-source"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_league_official",
    label: "Official league or tournament source",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["sports"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "medium",
    authorityProfile: "official",
    domainNotes: [
      "Template source id for tournament/champion markets where the exact league or tournament official URL is chosen per market.",
      "Do not publish with this generic id alone; contracts must replace it or attach a concrete official event URL."
    ],
    seerPath: "category-family-map-v1",
    createdAt: "2026-05-20T12:30:00Z",
    updatedAt: "2026-05-20T12:30:00Z",
    flags: ["template-source", "requires-exact-source-url", "verification-first"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_chainlink_data_streams",
    label: "Chainlink Data Streams",
    ownerLabel: "Chainlink",
    homepage: "https://data.chain.link/streams",
    primaryClass: "authority",
    accessSurface: "api",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["crypto"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "fast",
    noiseProfile: "low",
    authorityProfile: "high",
    domainNotes: [
      "Canonical oracle-feed candidate for crypto price/feed markets.",
      "Needs product source-policy review before replacing exchange candle settlement, because feed methodology differs from exchange close."
    ],
    seerPath: "category-family-map-v1",
    createdAt: "2026-05-20T12:30:00Z",
    updatedAt: "2026-05-20T12:30:00Z",
    flags: ["planned-fetch", "verification-first", "source-policy-review"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_protocol_official",
    label: "Protocol official source",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["crypto", "technology"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "medium",
    authorityProfile: "official",
    domainNotes: [
      "Template source id for protocol roadmap/upgrade markets.",
      "Usually requires a concrete project blog, governance page, release repo, or foundation notice before publish."
    ],
    seerPath: "category-family-map-v1",
    createdAt: "2026-05-20T12:30:00Z",
    updatedAt: "2026-05-20T12:30:00Z",
    flags: ["template-source", "requires-exact-source-url", "verification-first"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_github_releases",
    label: "GitHub Releases API",
    ownerLabel: "GitHub",
    homepage: "https://docs.github.com/rest/reference/releases",
    primaryClass: "authority",
    accessSurface: "api",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["technology", "crypto"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "low",
    authorityProfile: "high",
    domainNotes: [
      "Canonical API for repo release-by-date markets.",
      "Adapter must pin owner/repo, timezone, prerelease/draft policy, and tag matching rules."
    ],
    seerPath: "category-family-map-v1",
    createdAt: "2026-05-20T12:30:00Z",
    updatedAt: "2026-05-20T12:30:00Z",
    flags: ["planned-fetch", "verification-first", "official-technology-source"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_ietf_datatracker",
    label: "IETF Datatracker",
    ownerLabel: "IETF",
    homepage: "https://datatracker.ietf.org/api/",
    primaryClass: "authority",
    accessSurface: "api",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["technology"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "low",
    authorityProfile: "official",
    domainNotes: [
      "Official IETF Datatracker API for document/status workflow markets.",
      "Adapter must model the exact document stream/state, not generic keyword search."
    ],
    seerPath: "category-family-map-v1",
    createdAt: "2026-05-20T12:30:00Z",
    updatedAt: "2026-05-20T12:30:00Z",
    flags: ["planned-fetch", "verification-first", "official-technology-source"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_nvd_cve_api",
    label: "NVD CVE API",
    ownerLabel: "NIST National Vulnerability Database",
    homepage: "https://nvd.nist.gov/developers/vulnerabilities",
    primaryClass: "authority",
    accessSurface: "api",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["technology", "security"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "medium",
    authorityProfile: "official",
    domainNotes: [
      "Official NVD API for CVE publication/enrichment status.",
      "Known source-lag risk; markets must define whether they resolve on NVD publication, NVD enrichment, CVSS score, or another explicit field."
    ],
    seerPath: "category-family-map-v1",
    createdAt: "2026-05-20T12:30:00Z",
    updatedAt: "2026-05-20T12:30:00Z",
    flags: ["planned-fetch", "verification-first", "source-lag-risk"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_awards_official",
    label: "Official awards databases",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["culture", "awards"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "low",
    authorityProfile: "official",
    domainNotes: [
      "Umbrella source id for award bodies with official databases or winner pages.",
      "Known good anchors include Oscars official database and Television Academy awards search; exact award body URL is required per market."
    ],
    seerPath: "category-family-map-v1",
    createdAt: "2026-05-20T12:30:00Z",
    updatedAt: "2026-05-20T12:30:00Z",
    flags: ["template-source", "requires-exact-source-url", "verification-first"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_show_official",
    label: "Official show page",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["culture", "entertainment"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "medium",
    authorityProfile: "official",
    domainNotes: [
      "Template source id for reality/game-show winner or elimination markets.",
      "Israeli examples include official broadcaster/show pages such as Mako/Keshet for האח הגדול or המרוץ למיליון when a current season page exists.",
      "Final winner and elimination parsing is supported for exact official show pages with clear result language; episode/season release-before-deadline markets remain manual."
    ],
    lifecycleCapabilities: [
      {
        measurementKind: "final_winner",
        resultShape: "multi_outcome",
        oracleCapability: "supported_final_only",
        notes: ["Oracle official-show adapter can parse winner language from exact Mako/Keshet-style official show pages; scheduled close remains Horizon-owned."]
      },
      {
        measurementKind: "final_winner",
        resultShape: "yes_no",
        oracleCapability: "supported_final_only",
        notes: ["Oracle official-show adapter can resolve a binary child yes/no when the target couple wins, is eliminated, withdraws, or another known candidate wins."]
      },
      {
        measurementKind: "deadline_yes_no",
        resultShape: "yes_no",
        oracleCapability: "manual_resolution_required",
        notes: ["Use for episode/season release-before-deadline markets with exact official show page evidence."]
      }
    ],
    seerPath: "category-family-map-v1",
    createdAt: "2026-05-20T12:30:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    flags: ["template-source", "requires-exact-source-url", "verification-first", "source-lag-risk"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_kan_ipbc_show_pages",
    label: "Kan / IPBC official show pages",
    ownerLabel: "Israeli Public Broadcasting Corporation",
    homepage: "https://www.kan.org.il/",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["culture", "entertainment"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "medium",
    authorityProfile: "official",
    domainPatterns: ["kan.org.il"],
    domainNotes: [
      "Official broadcaster surface for Kan show pages and episodes.",
      "Contracts must attach the exact show/season/episode page; generic Kan homepage is not enough."
    ],
    lifecycleCapabilities: [
      {
        measurementKind: "deadline_yes_no",
        resultShape: "yes_no",
        oracleCapability: "manual_resolution_required",
        notes: ["Official source is grounded for episode/season release claims; Kan page parsing is not automated yet."]
      },
      {
        measurementKind: "official_value",
        resultShape: "yes_no",
        oracleCapability: "manual_resolution_required",
        notes: ["Use only with an exact official show page and human review."]
      }
    ],
    seerPath: "gta-vi-israel-event-source-hardening",
    createdAt: "2026-06-30T00:00:00Z",
    updatedAt: "2026-06-30T00:00:00Z",
    flags: ["planned-fetch", "verification-first", "requires-exact-source-url", "official-entertainment-source"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_ims_daily_observations",
    label: "Israel Meteorological Service daily observations",
    ownerLabel: "Israel Meteorological Service",
    homepage: "https://ims.gov.il/en/data_gov",
    primaryClass: "authority",
    accessSurface: "api",
    status: "trusted",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["weather"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "low",
    authorityProfile: "official",
    domainNotes: [
      "Official IMS daily observation source for Israeli station weather-threshold markets.",
      "Oracle adapter is credentialed through IMS_API_TOKEN and currently supports daily TDmax-style threshold markets.",
      "Operator capability checks must source the private ops env before treating credential_needed as a real blocker."
    ],
    lifecycleCapabilities: [
      {
        measurementKind: "threshold_crossing",
        resultShape: "yes_no",
        oracleCapability: "supported_final_only",
        notes: ["Oracle IMS adapter resolves daily station threshold markets after official data publication; scheduled close remains Horizon-owned."]
      },
      {
        measurementKind: "official_value",
        resultShape: "multi_outcome",
        oracleCapability: "supported_final_only",
        notes: ["Oracle IMS adapter resolves daily station value bucket markets after official data publication; scheduled close remains Horizon-owned."]
      }
    ],
    seerPath: "weather-family-sweep",
    createdAt: "2026-05-20T12:30:00Z",
    updatedAt: "2026-05-20T12:30:00Z",
    flags: ["live-fetch", "verification-first", "credential-required", "official-weather-source"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_noaa_cdo",
    label: "NOAA Climate Data Online API",
    ownerLabel: "NOAA NCEI",
    homepage: "https://www.ncei.noaa.gov/cdo-web/webservices/v2",
    primaryClass: "authority",
    accessSurface: "api",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["weather"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "low",
    authorityProfile: "official",
    domainNotes: [
      "Official NOAA/NCEI CDO API for station climate data.",
      "Requires API token and station/dataset mapping; useful global weather fallback, not the Israeli-first IMS path."
    ],
    seerPath: "category-family-map-v1",
    createdAt: "2026-05-20T12:30:00Z",
    updatedAt: "2026-05-20T12:30:00Z",
    flags: ["planned-fetch", "verification-first", "credential-required"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_openfda_drugs",
    label: "openFDA drug APIs",
    ownerLabel: "FDA",
    homepage: "https://open.fda.gov/apis/drug/",
    primaryClass: "authority",
    accessSurface: "api",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["health"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "medium",
    authorityProfile: "official",
    domainNotes: [
      "FDA/openFDA API surface for drug labels, events, enforcement, and related datasets.",
      "Approval markets must define the exact FDA/openFDA field and avoid interpreting clinical or safety meaning beyond the source."
    ],
    seerPath: "category-family-map-v1",
    createdAt: "2026-05-20T12:30:00Z",
    updatedAt: "2026-05-20T12:30:00Z",
    flags: ["planned-fetch", "verification-first", "health-policy-review"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_clinicaltrials_v2",
    label: "ClinicalTrials.gov API v2",
    ownerLabel: "ClinicalTrials.gov",
    homepage: "https://clinicaltrials.gov/data-api/about-api",
    primaryClass: "authority",
    accessSurface: "api",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["health"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "medium",
    authorityProfile: "official",
    domainNotes: [
      "Official ClinicalTrials.gov API v2 surface for study records/status.",
      "Markets must pin NCT id, status field, date basis, and update-lag/revision policy."
    ],
    seerPath: "category-family-map-v1",
    createdAt: "2026-05-20T12:30:00Z",
    updatedAt: "2026-05-20T12:30:00Z",
    flags: ["planned-fetch", "verification-first", "health-policy-review"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_moh_il",
    label: "Israel Ministry of Health databases",
    ownerLabel: "Israel Ministry of Health",
    homepage: "https://www.gov.il/he/service/health-registries",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["health"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "medium",
    authorityProfile: "official",
    domainNotes: [
      "Official Ministry of Health registry/database entry point for licensed products, professionals, organizations, and related public data.",
      "Source shape varies by registry; market contracts must name the exact registry/page before publish."
    ],
    lifecycleCapabilities: [
      {
        measurementKind: "official_value",
        resultShape: "yes_no",
        oracleCapability: "manual_resolution_required",
        notes: ["Local health-source grounding only; not a replacement for WHO on global pandemic declaration markets."]
      },
      {
        measurementKind: "deadline_yes_no",
        resultShape: "yes_no",
        oracleCapability: "manual_resolution_required",
        notes: ["Use only with an exact ministry publication and human review."]
      }
    ],
    seerPath: "category-family-map-v1",
    createdAt: "2026-05-20T12:30:00Z",
    updatedAt: "2026-05-20T12:30:00Z",
    flags: ["planned-fetch", "verification-first", "health-policy-review", "requires-exact-source-url"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_who_official",
    label: "World Health Organization official publications",
    ownerLabel: "World Health Organization",
    homepage: "https://www.who.int/",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["health", "science", "general"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "low",
    authorityProfile: "official",
    domainPatterns: ["who.int"],
    domainNotes: [
      "Official global health authority for WHO declarations, speeches, disease outbreak news, and emergency pages.",
      "Pandemic markets must require WHO language that explicitly declares or characterizes the outbreak as a global pandemic; PHEIC alone is not enough unless the visible rule says so."
    ],
    lifecycleCapabilities: [
      {
        measurementKind: "deadline_yes_no",
        resultShape: "yes_no",
        oracleCapability: "manual_resolution_required",
        notes: ["WHO official source is grounded; pandemic-declaration parsing is not automated yet."]
      },
      {
        measurementKind: "reported_claim",
        resultShape: "yes_no",
        oracleCapability: "manual_resolution_required",
        notes: ["Use as required official evidence in a human-gated credible-reporting policy."]
      }
    ],
    seerPath: "gta-vi-israel-event-source-hardening",
    createdAt: "2026-06-30T00:00:00Z",
    updatedAt: "2026-06-30T00:00:00Z",
    flags: ["planned-fetch", "verification-first", "requires-exact-source-url", "official-health-source"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_eia_open_data",
    label: "EIA Open Data API",
    ownerLabel: "U.S. Energy Information Administration",
    homepage: "https://www.eia.gov/opendata/documentation.php",
    primaryClass: "authority",
    accessSurface: "api",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["energy"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "low",
    authorityProfile: "official",
    domainNotes: [
      "Official EIA Open Data API for energy series.",
      "Requires API key and exact route/series mapping per market."
    ],
    seerPath: "category-family-map-v1",
    createdAt: "2026-05-20T12:30:00Z",
    updatedAt: "2026-05-20T12:30:00Z",
    flags: ["planned-fetch", "verification-first", "credential-required"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_energy_ministry_il",
    label: "Israel Ministry of Energy and Infrastructure",
    ownerLabel: "Israel Ministry of Energy and Infrastructure",
    homepage: "https://www.gov.il/he/departments/ministry_of_energy_and_infrastructure",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["energy"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "medium",
    authorityProfile: "official",
    domainNotes: [
      "Official Israeli ministry source for fuel, gas, energy infrastructure, and consumer price publications.",
      "Adapter needs a market-specific page/dataset such as fuel-price update, not generic ministry homepage scraping."
    ],
    seerPath: "category-family-map-v1",
    createdAt: "2026-05-20T12:30:00Z",
    updatedAt: "2026-05-20T12:30:00Z",
    flags: ["planned-fetch", "verification-first", "requires-exact-source-url"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_il_electricity_data",
    label: "Israel electricity system data",
    ownerLabel: "Noga - Israel Independent System Operator",
    homepage: "https://www.noga-iso.co.il/",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["energy"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "medium",
    authorityProfile: "official",
    domainNotes: [
      "Official Israeli electricity system operator surface.",
      "Need a stable public data endpoint before treating demand/production threshold markets as publish-ready."
    ],
    seerPath: "category-family-map-v1",
    createdAt: "2026-05-20T12:30:00Z",
    updatedAt: "2026-05-20T12:30:00Z",
    flags: ["planned-fetch", "verification-first", "requires-fetch-proof"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_moe_il_calendar",
    label: "Israel Ministry of Education calendar",
    ownerLabel: "Israel Ministry of Education",
    homepage: "https://pop.education.gov.il/maagal_hashana/",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["education"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "medium",
    authorityProfile: "official",
    domainNotes: [
      "Official Ministry of Education pedagogic calendar surface.",
      "Good for planned calendar milestones; adapter needs exact school-year/holiday semantics and source-lag policy."
    ],
    seerPath: "category-family-map-v1",
    createdAt: "2026-05-20T12:30:00Z",
    updatedAt: "2026-05-20T12:30:00Z",
    flags: ["planned-fetch", "verification-first", "official-education-source"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_moe_il_news",
    label: "Israel Ministry of Education notices",
    ownerLabel: "Israel Ministry of Education",
    homepage: "https://www.gov.il/he/departments/ministry_of_education",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["education"],
    primaryJobs: ["ground-confidence", "anchor-resolution"],
    speedProfile: "event-bound",
    noiseProfile: "medium",
    authorityProfile: "official",
    domainNotes: [
      "Official Ministry of Education department surface for notices and publications.",
      "Market contracts must attach the exact notice/news URL; generic department page is not enough for settlement."
    ],
    seerPath: "category-family-map-v1",
    createdAt: "2026-05-20T12:30:00Z",
    updatedAt: "2026-05-20T12:30:00Z",
    flags: ["planned-fetch", "verification-first", "requires-exact-source-url"]
  },
  {
    objectType: "source_registry_entry",
    sourceId: "src_imf_news",
    label: "IMF news and publications",
    ownerLabel: "International Monetary Fund",
    homepage: "https://www.imf.org/en",
    primaryClass: "authority",
    accessSurface: "html",
    status: "seeded",
    curationMode: "manual-seed",
    stageUsefulness: ["grounding", "review"],
    categoryFit: ["economy"],
    primaryJobs: ["explain-context", "ground-confidence"],
    speedProfile: "medium",
    noiseProfile: "low",
    authorityProfile: "official",
    domainNotes: ["Institutional macro layer for global stability, sovereign stress, and major policy context."],
    lifecycleCapabilities: [
      {
        measurementKind: "date_bucket",
        resultShape: "date_bucket",
        oracleCapability: "manual_resolution_required",
        notes: ["Use only when the specific IMF dataset/page URL is attached to the contract; adapter automation is not proven."]
      }
    ],
    seerPath: "research-seeded-fetch-roadmap",
    createdAt: "2026-04-08T11:00:00Z",
    updatedAt: "2026-04-08T11:00:00Z",
    flags: ["planned-fetch", "verification-first"]
  }
];
